// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_abm
List run_abm(List params);
RcppExport SEXP _MultiScaleABM_run_abm(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_abm(params));
    return rcpp_result_gen;
END_RCPP
}
// test_viral_load_trajectory
Rcpp::NumericVector test_viral_load_trajectory(int age_group, double dt, int VL_days, double I0, double baseline, Rcpp::NumericVector k, Rcpp::NumericVector gamma, Rcpp::NumericVector sigma);
RcppExport SEXP _MultiScaleABM_test_viral_load_trajectory(SEXP age_groupSEXP, SEXP dtSEXP, SEXP VL_daysSEXP, SEXP I0SEXP, SEXP baselineSEXP, SEXP kSEXP, SEXP gammaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type age_group(age_groupSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type VL_days(VL_daysSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< double >::type baseline(baselineSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(test_viral_load_trajectory(age_group, dt, VL_days, I0, baseline, k, gamma, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiScaleABM_run_abm", (DL_FUNC) &_MultiScaleABM_run_abm, 1},
    {"_MultiScaleABM_test_viral_load_trajectory", (DL_FUNC) &_MultiScaleABM_test_viral_load_trajectory, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiScaleABM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
